name: xpert

description: ""

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #For Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7

  #For Services locator
  get_it: ^7.6.7

  #For State Management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

  #For Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1

  #For Models class
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #For https services
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cookie_manager: ^3.1.1
  dio_http2_adapter: ^2.5.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor_hive_store: ^3.2.2
  connectivity_plus: ^2.3.8

  #For App Re-launch
  flutter_phoenix: ^1.1.1

  #For Native_Splash
  flutter_native_splash: ^2.3.10 #you can remove this 

  #For Ui
  image_picker: ^1.0.7
  dots_indicator: ^3.0.0
  fluttertoast: ^8.2.4
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^3.0.0
  bottom_picker: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/temp/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
